linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - goerr113
    - gomnd
    - lll
    - wsl
    - scopelint
    - maligned
    - golint
    - interfacer

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - testpackage
