name: GolangCI
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git config
        env:
          USER: edgelab-ci
          TOKEN: ${{ secrets.GOLANGCI_SECRET }}
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "ssh://git@github.com"
  
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Update dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
