name: GolangCI
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: git config --global url.git@github.com:edgelaboratories/.insteadOf https://github.com/edgelaboratories/
  
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Update dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
