name: golangci
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GOLANGCI_SECRET }}
        run: git config --global url."https://edgelab-ci:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=5m0s --build-tags=integration
