name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GOLANGCI_SECRET }}
        run: git config --global url."https://edgelab-ci:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Configure Git
        run: git config --global url.git@github.com:edgelaboratories/.insteadOf https://github.com/edgelaboratories/

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -race ./...
